---
# Головний файл задач для встановлення Jenkins
- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present
  become: yes

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present
  become: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  become: yes

- name: Ensure Jenkins is started and enabled on boot
  systemd:
    name: jenkins
    state: started
    enabled: yes
  become: yes

- name: Install Jenkins Plugins
  shell: >
    java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080/ install-plugin
    git matrix-auth workflow-aggregator docker-workflow blueocean credentials-binding git terraform -deploy
  args:
    executable: /bin/bash
  become: yes
  notify: restart jenkins

- name: Copy init Groovy script
  copy:
    src: init.groovy
    dest: /var/lib/jenkins/init.groovy.d/
  become: yes

- name: Restart Jenkins for init script
  systemd:
    name: jenkins
    state: restarted
  become: yes
