---
- name: Install and Configure Jenkins and Terraform
  hosts: localhost
  become: yes
  vars:
    jenkins_home: "/var/lib/jenkins"
    jenkins_config_path: "/var/jenkins_home/casc_configs"
    jenkins_plugins:
      - git
      - pipeline
      - job-dsl
      - blueocean
      - configuration-as-code
    terraform_version: "1.0.11"  # Specify the desired Terraform version
    terraform_install_path: "/usr/local/bin"

  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Wait for Jenkins to start
      wait_for:
        path: "/var/run/jenkins/jenkins.pid"

    - name: Install Jenkins plugins
      jenkins_plugin:
        name: "{{ item }}"
        jenkins_home: "{{ jenkins_home }}"
      loop: "{{ jenkins_plugins }}"
      notify: Restart Jenkins

    - name: Ensure Jenkins Configuration as Code directory exists
      file:
        path: "{{ jenkins_config_path }}"
        state: directory
        owner: jenkins
        group: jenkins

    - name: Copy JCasC configuration to Jenkins server
      copy:
        src: "./jenkins/jenkins-casc.yaml"
        dest: "{{ jenkins_config_path }}/jenkins-casc.yaml"
        owner: jenkins
        group: jenkins
        mode: '0644'

    - name: Install unzip (required for Terraform installation)
      apt:
        name: unzip
        state: present

    - name: Download Terraform
      get_url:
        url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: "/tmp/terraform.zip"
        mode: '0644'

    - name: Unzip Terraform
      ansible.builtin.unarchive:
        src: "/tmp/terraform.zip"
        dest: "{{ terraform_install_path }}"
        remote_src: yes
        creates: "{{ terraform_install_path }}/terraform"

    - name: Ensure Terraform binary is executable
      file:
        path: "{{ terraform_install_path }}/terraform"
        mode: '0755'

    - name: Restart Jenkins for JCasC reload
      systemd:
        name: jenkins
        state: restarted

  handlers:
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
