jenkins:
  systemMessage: "Jenkins configured automatically by JCasC"

  agentProtocols:
    - "JNLP4-connect"
    - "Ping"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "adminPassword"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      multibranchPipelineJob('Terraform-Deployment') {
        branchSources {
          git {
            id = 'terraform-deployment'
            remote = 'https://github.com/Diasastr/homework_23_iac_with_aws'
            traits {
              // Use specific Jenkinsfile path
              jenkinsFileFolder('jenkins/Terraform-Deployment')
            }
          }
        }
      }

  - script: >
      multibranchPipelineJob('Ansible-Configuration') {
        branchSources {
          git {
            id = 'terraform-deployment'
            remote = 'https://github.com/Diasastr/homework_23_iac_with_aws'
            traits {
            // Use specific Jenkinsfile path
            jenkinsFileFolder('jenkins/Ansible-Configuration')
            }
          }
        }
      }
  - script: >
      multibranchPipelineJob('Application-Deployment ') {
        branchSources {
          git {
            id = 'terraform-deployment'
            remote = 'https://github.com/Diasastr/homework_23_iac_with_aws'
            traits {
            // Use specific Jenkinsfile path
            jenkinsFileFolder('jenkins/Application-Deployment')
            }
          }
        }
      }
