jenkins:
  systemMessage: "Jenkins configured automatically by JCasC"

  agentProtocols:
    - "JNLP4-connect"
    - "Ping"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "adminPassword"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      multibranchPipelineJob('Terraform-Deployment') {
        branchSources {
          git {
            id = 'terraform-deployment'
            remote = 'https://github.com/Diasastr/homework_23_iac_with_aws/blob/68f2f4588b0abb43ae697836d149e4a04c655b69/jenkins/Terraform-Deployment'
          }
        }
      }
  - script: >
      multibranchPipelineJob('Ansible-Configuration') {
        branchSources {
          git {
            id = 'terraform-deployment'
            remote = 'https://github.com/Diasastr/homework_23_iac_with_aws/blob/52ba0b3bac7e0591813e017851012a004bff5f01/jenkins/Ansible-Configuration'
          }
        }
      }
  - script: >
      multibranchPipelineJob('Application-Deployment ') {
        branchSources {
          git {
            id = 'terraform-deployment'
            remote = 'https://github.com/Diasastr/homework_23_iac_with_aws/blob/52ba0b3bac7e0591813e017851012a004bff5f01/jenkins/Application-Deployment'
          }
        }
      }
