pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                // Checkout the repository containing Terraform files
                checkout scm
            }
        }
        stage('Terraform') {
            steps {
                script {
                    // Change directory to the Terraform deployment folder
                    dir('jenkins/Terraform-Deployment') {
                        // Initialize Terraform
                        sh 'terraform init'

                        // (Optional) Validate Terraform configuration
                        sh 'terraform validate'

                        // Apply Terraform changes
                        sh 'terraform apply -auto-approve -lock=false'

                        // (Optional) Output Terraform execution plan
                        sh 'terraform plan'

                        // (Optional) Destroy Terraform resources
                        // sh 'terraform destroy -auto-approve'
                    }
                }
            }
        }
    }
}
